/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.lang.reflect.Array;
import java.util.ArrayList;
import java.util.Arrays;

/**
 *
 * @author Ruth
 */
public class Pantalla extends javax.swing.JFrame {

    /**
     * Creates new form Patalla
     */
    public Pantalla() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu1 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        bt1 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btMas = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        btMenos = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        btDividir = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btComa = new javax.swing.JButton();
        btIgual = new javax.swing.JButton();
        btPor = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt2 = new javax.swing.JTextField();
        txt = new javax.swing.JTextField();

        jMenu1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jMenu1.setText("jMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new java.awt.GridLayout(4, 4));

        bt1.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });
        jPanel1.add(bt1);

        bt2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });
        jPanel1.add(bt2);

        bt3.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });
        jPanel1.add(bt3);

        btMas.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btMas.setText("+");
        btMas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMasActionPerformed(evt);
            }
        });
        jPanel1.add(btMas);

        bt4.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });
        jPanel1.add(bt4);

        bt5.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });
        jPanel1.add(bt5);

        bt6.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });
        jPanel1.add(bt6);

        btMenos.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btMenos.setText("-");
        btMenos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenosActionPerformed(evt);
            }
        });
        jPanel1.add(btMenos);

        bt7.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });
        jPanel1.add(bt7);

        bt8.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });
        jPanel1.add(bt8);

        bt9.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });
        jPanel1.add(bt9);

        btDividir.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btDividir.setText("/");
        btDividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDividirActionPerformed(evt);
            }
        });
        jPanel1.add(btDividir);

        bt0.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });
        jPanel1.add(bt0);

        btComa.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btComa.setText(".");
        btComa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btComaActionPerformed(evt);
            }
        });
        jPanel1.add(btComa);

        btIgual.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btIgual.setText("=");
        btIgual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btIgualActionPerformed(evt);
            }
        });
        jPanel1.add(btIgual);

        btPor.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        btPor.setText("x");
        btPor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPorActionPerformed(evt);
            }
        });
        jPanel1.add(btPor);

        jPanel3.setLayout(new java.awt.GridLayout(2, 0));

        txt2.setBorder(null);
        jPanel3.add(txt2);

        txt.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txt.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jPanel3.add(txt);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 439, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        txt.setText(txt.getText()+ 1);
    }//GEN-LAST:event_bt1ActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        txt.setText(txt.getText()+ 2);
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        txt.setText(txt.getText()+ 3);
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        txt.setText(txt.getText()+ 4);
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        txt.setText(txt.getText()+ 5);
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        txt.setText(txt.getText()+ 6);
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        txt.setText(txt.getText()+ 7);
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        txt.setText(txt.getText()+ 8);
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        txt.setText(txt.getText()+ 9);
    }//GEN-LAST:event_bt9ActionPerformed

    private void btComaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btComaActionPerformed
        txt.setText(txt.getText()+ ".");
    }//GEN-LAST:event_btComaActionPerformed

    private void btIgualActionPerformed(java.awt.event.ActionEvent evt) {
        txt2.setText(txt.getText());

        //1) separo en terminos con operador resta
        String[] array1 = txt.getText().split("-");

        //2) agrego el - al principio de cada término. La posicion 0 NO porque o es positiva o es "".
        for (int i=1; i<array1.length; i++){
            array1[i] = "-" + array1[i];
        }

        //3) Separo en terminos con +
        ArrayList<String> listaTerminos1 = new ArrayList<String>();
        for (String termino: array1
             ) {
            String[] aux = termino.split("\\+");
            // agrego los terminos a sumar en una lista
            for (String terminoAux: aux
                 ) {
                listaTerminos1.add(terminoAux);
            }
        }
        ///remueno el termino vacío que se agrego en caso de que la operación comenzara con -. Ej: -3+4*5
        listaTerminos1.remove("");

        /// 4) Resuelvo operaciones * y / (Sólo se puede resolver una op por termino)
        ArrayList<String> terminosAux = new ArrayList<String>();
        ///primero los *
        for (int i=0; i < listaTerminos1.size(); i++){
            String[] aux =  listaTerminos1.get(i).split("\\*");
            if (aux.length>1){
                float terminoNuevo = 1;
                for (String factor: aux
                ) {
                    terminoNuevo = terminoNuevo * Float.parseFloat(factor);
                }
                listaTerminos1.remove(i);
                terminosAux.add("" + terminoNuevo);
            }
            listaTerminos1.addAll(terminosAux);
            terminosAux.clear();
        }
        for (int i=0; i < listaTerminos1.size(); i++){
            String[] aux =  listaTerminos1.get(i).split("/");
            if (aux.length>1){
                float nro1 = Float.parseFloat(aux[0]);
                float nro2 = Float.parseFloat(aux[1]);
                float razon = nro1/nro2;
                listaTerminos1.remove(i);
                terminosAux.add("" + razon);
            }
            listaTerminos1.addAll(terminosAux);
            terminosAux.clear();
        }
        float rta = 0;
        for (String termino: listaTerminos1
             ) {
            rta += Float.parseFloat(termino);
        }
        txt.setText("" + rta);
    }                                       

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
       txt.setText(txt.getText()+ 0);
    }//GEN-LAST:event_bt0ActionPerformed

    private void btDividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDividirActionPerformed
        txt.setText(txt.getText()+ "/");
    }//GEN-LAST:event_btDividirActionPerformed

    private void btPorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPorActionPerformed
        txt.setText(txt.getText()+ "*");
    }//GEN-LAST:event_btPorActionPerformed

    private void btMasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMasActionPerformed
        txt.setText(txt.getText()+ "+");
    }//GEN-LAST:event_btMasActionPerformed

    private void btMenosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenosActionPerformed
        txt.setText(txt.getText()+ "-");
    }//GEN-LAST:event_btMenosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btComa;
    private javax.swing.JButton btDividir;
    private javax.swing.JButton btIgual;
    private javax.swing.JButton btMas;
    private javax.swing.JButton btMenos;
    private javax.swing.JButton btPor;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txt;
    private javax.swing.JTextField txt2;

    // End of variables declaration//GEN-END:variables
}
